### ISSUE TITLE
Profile Photo Hide future

### ISSUE THREAD

**Issue by Siva10geeth** [Raj10siva/WhatsApp_Project1#3]
Hello Raj,

This is Sivakumar.
It would be the great application if you add profile photo hiding feature in WhatsApp.
Kindle please add it and your work will be awesome!!!

**Comment by Raj10siva** [comment]
Dear SivaKumar,

Thanks for contributing for our project.
Yeah, it's a great idea Siva!!!
I will try to add this feature and update you as soon as possible my friend.

**Comment by Raj10siva** [comment]
Dear Siva,

Thanks for showing interest in our project.
I've successfully added the profile picture hiding feature in the WhatsApp project.
Kindly use it and ask any doubts or questions regarding this!



Thank you!
